# Generated by Django 5.1.4 on 2026-08-08 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai', '0001_initial'),
        ('properties', '0002_matchscore'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='voicenote',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_notes', to='sales.deal'),
        ),
        migrations.AddField(
            model_name='voicenote',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_notes', to='properties.property'),
        ),
        migrations.AddField(
            model_name='voicenote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='voicenote',
            index=models.Index(fields=['user', 'status'], name='voice_notes_user_id_eda460_idx'),
        ),
        migrations.AddIndex(
            model_name='voicenote',
            index=models.Index(fields=['client', 'status'], name='voice_notes_client__e5f527_idx'),
        ),
    ]
