export { default as authApi } from './auth'
export { default as usersApi } from './users'
export { default as clientsApi } from './clients'
export { default as propertiesApi } from './properties'
export { default as salesApi } from './sales'
export { default as activitiesApi } from './activities'
export { default as tasksApi } from './tasks'
export { default as notificationsApi } from './notifications'
export { default as dashboardApi } from './dashboard'
export { default as reportsApi } from './reports'
export { default as settingsApi } from './settings'
export { default as searchApi } from './search'

// Export factory for advanced usage
export { createResource, createSubResource, createSingleton } from '../resourceFactory'
