# Generated by Django 5.1.4 on 2026-08-08 08:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('matched_fields', models.JSONField(blank=True, default=list)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_scores', to='clients.client')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_scores', to='properties.property')),
            ],
            options={
                'db_table': 'match_scores',
                'ordering': ['-score'],
                'indexes': [models.Index(fields=['client', 'score'], name='match_score_client__9aa124_idx'), models.Index(fields=['property', 'score'], name='match_score_propert_479866_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('client', 'property'), name='unique_active_client_property_match')],
            },
        ),
    ]
