# Generated by Django 5.1.4 on 2026-08-08 08:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('full_name', models.CharField(db_index=True, max_length=255)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('email', models.EmailField(blank=True, db_index=True, default='', max_length=254)),
                ('source', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('New', 'New'), ('Contacted', 'Contacted'), ('Qualified', 'Qualified'), ('Unqualified', 'Unqualified'), ('Negotiating', 'Negotiating'), ('Won', 'Won'), ('Lost', 'Lost'), ('Archived', 'Archived')], db_index=True, default='New', max_length=20)),
                ('customer_type', models.CharField(blank=True, default='', max_length=100)),
                ('budget_min', models.BigIntegerField(default=0)),
                ('budget_max', models.BigIntegerField(default=0)),
                ('preferred_areas', models.JSONField(blank=True, default=list)),
                ('preferred_property_types', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True, default='')),
                ('score', models.PositiveIntegerField(default=0)),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_clients', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_clients', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'clients',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='clients_status_9957f9_idx'), models.Index(fields=['assigned_agent', 'status'], name='clients_assigne_af9c4c_idx'), models.Index(fields=['customer_type', 'status'], name='clients_custome_0ab4ff_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False), models.Q(('phone', ''), _negated=True)), fields=('phone',), name='unique_active_client_phone')],
            },
        ),
    ]
