# Generated by Django 5.1.4 on 2026-08-08 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        ('properties', '0002_matchscore'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to='sales.deal'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to='properties.property'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['client', 'occurred_at'], name='interaction_client__50d3c5_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['deal', 'occurred_at'], name='interaction_deal_id_ef3bd8_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['needs_followup', 'followup_at'], name='interaction_needs_f_fddb5f_idx'),
        ),
    ]
