# Generated by Django 5.1.4 on 2026-08-08 08:29

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('properties', '0002_matchscore'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'pipelines',
                'ordering': ['sort_order', 'created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_deleted', False)), fields=('name',), name='unique_active_pipeline_name')],
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(default='#3b82f6', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_won_stage', models.BooleanField(default=False)),
                ('is_lost_stage', models.BooleanField(default=False)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='sales.pipeline')),
            ],
            options={
                'db_table': 'stages',
                'ordering': ['pipeline', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('amount', models.BigIntegerField(default=0)),
                ('probability', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('expected_close_date', models.DateField(blank=True, db_index=True, null=True)),
                ('source', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Won', 'Won'), ('Lost', 'Lost')], db_index=True, default='Open', max_length=10)),
                ('lost_reason', models.CharField(blank=True, default='', max_length=255)),
                ('won_reason', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_deals', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='properties.property')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_deals', to=settings.AUTH_USER_MODEL)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='sales.pipeline')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='sales.stage')),
            ],
            options={
                'db_table': 'deals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='stage',
            index=models.Index(fields=['pipeline', 'sort_order'], name='stages_pipelin_70a891_idx'),
        ),
        migrations.AddConstraint(
            model_name='stage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('pipeline', 'sort_order'), name='unique_active_stage_order_per_pipeline'),
        ),
        migrations.AddConstraint(
            model_name='stage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('pipeline', 'name'), name='unique_active_stage_name_per_pipeline'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['pipeline', 'stage'], name='deals_pipelin_ffed59_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['agent', 'status'], name='deals_agent_i_6e8304_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['expected_close_date', 'status'], name='deals_expecte_c4488b_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['client', 'status'], name='deals_client__999d78_idx'),
        ),
    ]
